# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e22a97cd9552c1fdb9b5f46fd37d5bc28180c13e5bb02ae8812546b6e384717f1a1c3e89d5511b7cc0b4b04a7cce5842a263b329fa6b8801a15373e493b5ef1

test:
  secret_key_base: 06f2f3e3c623fbdcb1e6294821dec2a1a0d81c87df8465e647c5d4c916bae908b2356cb8289a9754e0c7d18c06bdb39dd0af051823691823c67da7540f5b2ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
